-- PostgreSQL: executar com a conta de migração, após backup e em homologação primeiro.
-- Idempotente. Não modifica contas, postagens ou fotos existentes.
BEGIN;
CREATE TABLE IF NOT EXISTS user_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS convite_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL,
    expira_em TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    utilizado_em TIMESTAMP(6) WITH TIME ZONE,
    revogado_em TIMESTAMP(6) WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_convite_admin_expira ON convite_admin(expira_em);
COMMIT;
