spring.application.name=tcc-backend

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


api.security.token.secret=${JWT_SECRET:4zY9kL2pQ8vR1wX3sN6mT0uB7vC5xZ8yA1bC3dE5fG7hI9jK}

# Configuração do PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configurações do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true